error_code_dict = {
    600: 'REQUEST FAILED',
    601: 'loss argument',
    610: 'ACCOUNT IS REGISTER',
    611: 'ACCOUNT IS INVALID',
    612: 'PASSWORD LENGTH IS INVALID',
    613: 'INVALID GOOGLE TOKEN',
    620: 'LOGIN_ERROR',
    621: 'ACCOUNT NOT LOGIN',
    630: 'USER IS EXIST',
    640: 'RECOGNIZED FAILED',
    641: 'DATABASE NO DATA CAN RECOGNIZED',
    642: 'INVALID CLOCKIN STATUS',
    650: 'INVALID IMAGE FORMAT'
}
